config/routes.rb
ODCNavigatorPosts::Application.routes.draw do
  resources :posts, except: :show

   root 'posts#index'

   get '/login' => 'login#login'
   post '/login' => 'login#sign_in'
   get '/logout' => 'login#sign_out'
   post '/image' => 'posts#month_image'

  

end

app/models/month_image.rb
class MonthImage < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "960x178>", :thumb => "100x100>" }, :default_url => "/images/January.png"
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include LoginHelper
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
  end
  
  def sign_in
  	user = User.find_by(name: params[:user][:name])
  	if user && user.password == params[:user][:password] then signin(user)
    else
      flash.now[:error] = 'Invalid email/password combination' 
      render 'login'
    end
  end

  def sign_out
  	signout
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :signedin, only: [:new, :edit, :create, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts_all = Post.all
    @posts_months = @posts_all.group_by { |post| post.created_at.strftime("%B") }
    
    if params[:month].present?
      @posts = @posts_months[params[:month]]
      @image_month = MonthImage.find_by(month: params[:month])
    else
      @posts = []
      @posts = @posts_months[Time.now.strftime("%B")] if @posts_months[Time.now.strftime("%B")]
      @image_month = MonthImage.find_by(month: Time.now.strftime("%B"))
      #@posts = Post.where(:created_at => Time.now.beginning_of_month..Time.now.end_of_month)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  #def show
  #end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  
  def month_image
     month_image = MonthImage.find_by(month: params[:month]) || MonthImage.new(:month => params[:month])
     month_image.update_attributes!(:image => params[:image])
     redirect_to 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
	def signin(user)
		session[:user_id] = user.id
		
		redirect_to '/posts'
	end

	def signout
		session[:user_id] = nil
		
		redirect_to '/posts'
	end 

	def signedin
  	redirect_to '/login' if session[:user_id].nil?
    end

    def signed_in?
	  true unless session[:user_id].nil?
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ODCNavigatorPosts</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	  <!-- <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ODC Navigator Blog</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li ><% if signed_in? %>
                  <%= link_to 'Logout', logout_path %>
                  <% else %>
                  <%= link_to 'Login', login_path %>
                  <% end %>
            </li>
          </ul>
        </div><!/.nav-collapse 
      </div>
    </div>-->
    
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<%= yield %>
</body>
</html>

app/views/login/login.html.erb
<div class="login">
 <div class="container">
 	<div class="row">
 		<div class="col-sm-offset-3 col-sm-9">
<p style="color:rgb(66,139,202)"><b> Please login!</b></p>
 <%= form_tag do%>
  <div class="row">
  	<div class="col-sm-3">
  <%= label_tag :Name %>
   </div>
   <div class="col-sm-9">
  <%= text_field(:user, :name)%>
  </div>
</div>
<div class="row">
	<div class="col-sm-3">
  <%= label_tag :Password %>
</div>
<div class="col-sm-9">
  <%= text_field(:user, :password) %>
</div>
</div>
<div class="row">
<div class="col-sm-offset-3 col-sm-9">
  <%= submit_tag 'Login' , class: 'btn btn-primary btn-sm' %>
</div>
</div>
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/posts/_form.html.erb
<div class="form">
  <div class="container">
    <div class="row">
      <div class="col-sm-offset-2 col-sm-9">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title, id: 'title' %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, id: 'content' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
</div>
</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>


<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
    <div class="static1">
      <div class="head">
        <div class="container">
        <h1>ODC Navigator News</h1>
        <ul class="navlist">
        <% if signed_in? %>
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'Logout', logout_path %></li>
        <% end %>
        <ul>
      </div>
      </div>
      <div class="image">
      <div class="container">

        <% if @image_month %>
          <%= image_tag @image_month.image.url %>
        <% else %>
          <%= image_tag 'default.jpg' %>
        <% end %>
      </div>
    </div>
  </div>
    <div class="blog-content">
    <div class="container">
      <div class="row">
      <div class="col-lg-10 col-sm-10">
        <% @posts.each do |post| %>
        <div class="post">
          <div class="title">
            <%= post.title %>
          </div>
          <div class="date">
            <%= post.created_at.strftime("%d %B %Y") %>
          </div>
          <hr></hr>
          <div class="content">
            <%= post.content %>
          </div>
          <div class="edit">
            <% if signed_in? %>
              <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-primary btn-sm' %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm'%>
            <% end %>
          </div> 
        </div>
          <br>
        <% end %>
        <% if signed_in? %>
          <div>
            <%= form_tag '/image', multipart: true do %>
              <%= select_tag 'month', options_for_select(@posts_months.keys) %>          
              <label for="file">File to Upload</label> <%= file_field_tag "image" %>
              <%= submit_tag %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-lg-2 col-sm-2" >
        <div style="text-align:center" id="archive">ARCHIVES</div>
        <% for key in @posts_months.keys do %>
        <div class="months">
        <%= link_to key, posts_path(:month => key)%>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="new-post">
<%= render 'form' %>
<%= link_to 'Back', posts_path, class: 'btn btn-primary btn-sm', id: 'back' %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>